<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE RegAdmin [
	<!ELEMENT RegAdmin (Sensores,Calendario)>
	<!ELEMENT Sensores (Temperatura)*>
	<!ELEMENT Temperatura (id, alias)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT alias (#PCDATA)>
	<!ELEMENT Calendario (usuario,contrase単a)>
	<!ATTLIST Calendario tipo CDATA #REQUIRED>
	<!ELEMENT usuario (#PCDATA)>
	<!ELEMENT contrase単a (#PCDATA)>
]>
<RegAdmin>
	<Sensores>
		<Temperatura>
			<id>28f5e9zf020000d2</id>
			<alias>Sensor superior</alias>
		</Temperatura>
		<Temperatura>
			<id>282ddbaf020000b0</id>
			<alias>Sensor inferior</alias>
		</Temperatura>
	</Sensores>
	<Calendario tipo="gmail">
		<usuario>sysreg1</usuario>
		<contrase単a>agricultura.1</contrase単a>
	</Calendario>
</RegAdmin>